"""
title: Stetson Admissions Email Assistant
description: Send helpful admissions emails to prospective students (Admin Only)
author: DME-CPH Team
version: 1.0.0
requirements: smtplib, email
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Optional, Literal
import logging
from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings, SettingsConfigDict

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class Tools:
    class Valves(BaseSettings):
        """Email configuration settings"""
        SMTP_SERVER: str = Field(
            default="smtp.gmail.com",
            description="SMTP server address"
        )
        SMTP_PORT: int = Field(
            default=465,
            description="SMTP server port (465 for SSL, 587 for TLS)"
        )
        USE_SSL: bool = Field(
            default=True,
            description="Use SSL (True) or TLS (False)"
        )
        FROM_EMAIL: str = Field(
            default="admissions@stetson.edu",
            description="Sender email address"
        )
        FROM_NAME: str = Field(
            default="Addi - Stetson Admissions",
            description="Sender display name"
        )
        EMAIL_PASSWORD: str = Field(
            default="",
            description="Email account password or app password"
        )
        ADMIN_ONLY: bool = Field(
            default=True,
            description="Restrict email sending to admins only"
        )
        REQUIRE_CONFIRMATION: bool = Field(
            default=True,
            description="Require user confirmation before sending"
        )
        
        model_config = SettingsConfigDict(
            env_prefix='STETSON_EMAIL_',
            case_sensitive=True
        )
    
    def __init__(self):
        self.valves = self.Valves()
        self.citation = True
        
        # Email templates for common scenarios
        self.templates = {
            "application_info": {
                "subject": "Stetson University Application Information",
                "template": """Dear {name},

Thank you for your interest in Stetson University! I'm Addi, your AI admissions assistant.

Here's the information you requested about our application process:

{content}

Additional Resources:
• Online Application: https://apply.stetson.edu
• Financial Aid Calculator: https://stetson.edu/financial-aid/calculator
• Campus Visits: Call (386) 822-7100 or visit stetson.edu/visit

If you have any questions, feel free to ask me or contact our Office of Admissions at admissions@stetson.edu or (386) 822-7100.

Best regards,
Addi
AI Admissions Assistant
Stetson University

---
This email was generated by an AI assistant. For official correspondence, please contact the Office of Admissions directly.
"""
            },
            "campus_tour": {
                "subject": "Stetson Campus Visit Information",
                "template": """Dear {name},

I'm excited to help you schedule your visit to Stetson University!

{content}

To schedule your campus tour:
• Call: (386) 822-7100
• Email: admissions@stetson.edu
• Online: stetson.edu/visit

Tour Information:
• Tours available Monday-Friday at 10am and 2pm
• Campus tour + admissions presentation (~2 hours)
• Optional: Attend a class, meet with professors, lunch in dining hall

We can't wait to show you our beautiful 175-acre campus in historic DeLand!

Best regards,
Addi
AI Admissions Assistant
Stetson University

---
This email was generated by an AI assistant. For official scheduling, please contact our Office of Admissions.
"""
            },
            "financial_aid": {
                "subject": "Stetson Financial Aid Information",
                "template": """Dear {name},

Thank you for asking about financial aid at Stetson University!

{content}

Important Deadlines:
• Priority FAFSA Deadline: February 15
• CSS Profile Recommended: March 1
• Financial Aid Awards Sent: April 1

Resources:
• Net Price Calculator: stetson.edu/financial-aid/calculator
• Financial Aid Office: (386) 822-7120 or financialaid@stetson.edu
• Scholarship Information: stetson.edu/scholarships

Over 95% of our students receive financial assistance - we're here to help make Stetson affordable!

Best regards,
Addi
AI Admissions Assistant
Stetson University

---
This email was generated by an AI assistant. For personalized financial aid counseling, please contact our Office of Financial Aid.
"""
            },
            "general": {
                "subject": "Information from Stetson University",
                "template": """Dear {name},

Thank you for contacting Stetson University!

{content}

For additional questions, please don't hesitate to reach out:
• Admissions Office: (386) 822-7100 or admissions@stetson.edu
• Website: www.stetson.edu
• Visit Campus: stetson.edu/visit

We look forward to hearing from you!

Best regards,
Addi
AI Admissions Assistant
Stetson University

---
This email was generated by an AI assistant. For official correspondence, please contact the appropriate Stetson office directly.
"""
            }
        }
        
        logger.info("Stetson Email Tool initialized")
    
    def send_stetson_email(
        self,
        recipient_email: str,
        recipient_name: str,
        email_type: Literal["application_info", "campus_tour", "financial_aid", "general"] = "general",
        content: str = "",
        custom_subject: Optional[str] = None,
        __user__: dict = {},
        __event_emitter__=None
    ) -> str:
        """
        Send helpful admissions emails to prospective students.
        
        **IMPORTANT:** This tool REQUIRES user confirmation before sending.
        You must show the user the email content and get their explicit approval.
        
        **Admin Only:** By default, only administrators can send emails.
        
        **Email Types:**
        - "application_info": Information about applying to Stetson
        - "campus_tour": Campus visit scheduling and information
        - "financial_aid": Scholarship and financial aid details
        - "general": General information or custom content
        
        **Example Usage:**
        1. User asks to send application info to a prospective student
        2. You compose the email content
        3. You show it to the user and ask for confirmation
        4. After user confirms "yes, send it", you call this function
        
        :param recipient_email: Email address to send to
        :param recipient_name: Recipient's name (for personalization)
        :param email_type: Type of email template to use
        :param content: Main content to include in the email
        :param custom_subject: Optional custom subject line
        :return: Confirmation message or error
        """
        
        try:
            # Admin check
            if self.valves.ADMIN_ONLY:
                user_role = __user__.get("role", "user")
                if user_role != "admin":
                    logger.warning(f"Non-admin attempted to send email: {__user__.get('name', 'Unknown')}")
                    return "🔒 Email sending is restricted to administrators. Please contact your supervisor."
            
            # Validate configuration
            if not self.valves.EMAIL_PASSWORD:
                return "⚠️ Email is not configured. Please set EMAIL_PASSWORD in tool settings."
            
            if self.valves.FROM_EMAIL == "admissions@stetson.edu" and "@stetson.edu" not in self.valves.FROM_EMAIL:
                return "⚠️ Invalid FROM_EMAIL configuration. Please update in tool settings."
            
            # Reminder about confirmation requirement
            if self.valves.REQUIRE_CONFIRMATION:
                logger.info(f"Email send requested by {__user__.get('name', 'Unknown')} to {recipient_email}")
            
            # Get template
            template_data = self.templates.get(email_type, self.templates["general"])
            subject = custom_subject or template_data["subject"]
            
            # Format email body
            body = template_data["template"].format(
                name=recipient_name,
                content=content
            )
            
            # Create email message
            msg = MIMEMultipart('alternative')
            msg["Subject"] = subject
            msg["From"] = f"{self.valves.FROM_NAME} <{self.valves.FROM_EMAIL}>"
            msg["To"] = recipient_email
            msg["Reply-To"] = self.valves.FROM_EMAIL
            
            # Add plain text part
            text_part = MIMEText(body, 'plain')
            msg.attach(text_part)
            
            # Send via SMTP
            logger.info(f"Sending email to {recipient_email}: {subject}")
            
            try:
                if self.valves.USE_SSL:
                    with smtplib.SMTP_SSL(self.valves.SMTP_SERVER, self.valves.SMTP_PORT, timeout=30) as server:
                        server.login(self.valves.FROM_EMAIL, self.valves.EMAIL_PASSWORD)
                        server.send_message(msg)
                else:
                    with smtplib.SMTP(self.valves.SMTP_SERVER, self.valves.SMTP_PORT, timeout=30) as server:
                        server.starttls()
                        server.login(self.valves.FROM_EMAIL, self.valves.EMAIL_PASSWORD)
                        server.send_message(msg)
                
                logger.info(f"✓ Email sent successfully to {recipient_email}")
                
                return f"""✅ **Email Sent Successfully!**

**To:** {recipient_email}
**Subject:** {subject}
**Type:** {email_type}

The prospective student should receive the email shortly. You can follow up with them to ensure they received it.
"""
            
            except smtplib.SMTPAuthenticationError:
                logger.error("SMTP authentication failed")
                return "❌ **Email Authentication Failed**\n\nThe email password is incorrect or the account requires an app-specific password. Please update EMAIL_PASSWORD in tool settings."
            
            except smtplib.SMTPException as e:
                logger.error(f"SMTP error: {e}")
                return f"❌ **Email Send Failed**\n\nSMTP Error: {str(e)}\n\nPlease check your SMTP settings and try again."
            
            except Exception as e:
                logger.error(f"Email error: {e}")
                return f"❌ **Email Send Failed**\n\nError: {str(e)}\n\nPlease contact a system administrator."
        
        except Exception as e:
            logger.exception(f"Unexpected error sending email")
            return f"❌ **Unexpected Error**\n\nFailed to send email. Error: {str(e)}"
    
    def preview_email(
        self,
        recipient_name: str,
        email_type: Literal["application_info", "campus_tour", "financial_aid", "general"] = "general",
        content: str = ""
    ) -> str:
        """
        Preview an email before sending (for user confirmation).
        
        **Use this first** to show the user what will be sent, then ask for confirmation.
        
        :param recipient_name: Recipient's name
        :param email_type: Type of email template
        :param content: Content to include
        :return: Formatted email preview
        """
        template_data = self.templates.get(email_type, self.templates["general"])
        subject = template_data["subject"]
        
        body = template_data["template"].format(
            name=recipient_name,
            content=content
        )
        
        preview = f"""**📧 Email Preview**

**Subject:** {subject}
**Template:** {email_type}

---

{body}

---

**Would you like me to send this email?** Please reply with:
- "Yes, send it" to proceed
- "No" or "Cancel" to abort
- Or ask me to modify the content
"""
        
        return preview
    
    def get_template_info(self) -> str:
        """
        Get information about available email templates.
        
        :return: List of available templates and their purposes
        """
        info = "**📧 Available Email Templates:**\n\n"
        
        descriptions = {
            "application_info": "Application process, requirements, and deadlines",
            "campus_tour": "Campus visit scheduling and tour information",
            "financial_aid": "Scholarships, financial aid, and cost information",
            "general": "General Stetson information or custom content"
        }
        
        for template_name, description in descriptions.items():
            info += f"**{template_name}**\n"
            info += f"  • {description}\n"
            info += f"  • Subject: {self.templates[template_name]['subject']}\n\n"
        
        info += "\n**Usage:**\n"
        info += "1. First, use `preview_email()` to show the user what will be sent\n"
        info += "2. Get user confirmation\n"
        info += "3. Then use `send_stetson_email()` to send\n"
        
        return info

